modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/mc-wiki/minecraft-mod-heywiki/issues"

[[mods]]
modId = "heywiki"
version = "${version}"
displayName = "Hey Wiki"
displayUrl = "https://minecraft.wiki/w/MCW:Hey_Wiki"
authors = "Minecraft Wiki"
description = '''
Press H to open the Minecraft Wiki page of the block/item/entity you're aiming at.
'''
logoFile = "icon.png"

[[mixins]]
#config = "heywiki.mixins.json"
config = "heywiki-common.mixins.json"

[[dependencies.heywiki]]
modId = "neoforge"
type = "required"
versionRange = "[21.6.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.heywiki]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.heywiki]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "CLIENT"
[dependencies.heywiki.mc-publish]
modrinth = "architectury-api"
curseforge = "architectury-api"

[[dependencies.heywiki]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.0,)"
ordering = "AFTER"
side = "CLIENT"
[dependencies.heywiki.mc-publish]
modrinth = "cloth-config"
curseforge = "cloth-config"

[[dependencies.heywiki]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "[15.0.0,)"
ordering = "AFTER"
side = "CLIENT"
[dependencies.heywiki.mc-publish]
modrinth = "rei"
curseforge = "roughly-enough-items"

[[dependencies.heywiki]]
modId = "emi"
type = "optional"
versionRange = "[1.1.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.heywiki]]
modId = "jei"
type = "optional"
versionRange = "[19.0.0,)"
ordering = "AFTER"
side = "CLIENT"
